# Generated by Django 5.0.6 on 2024-05-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_type', models.CharField(max_length=20)),
                ('log_message', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('read', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('humidity_threshold', models.FloatField()),
                ('notification_method', models.CharField(max_length=20)),
                ('fan_duration', models.IntegerField()),
                ('alarm', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureHumidityData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UltrasonicData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
