# Generated by Django 5.0.6 on 2024-06-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrellaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultrasonicdata',
            name='distance',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
